config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :amo_accounts
  root to: "amo_accounts#index"
  scope '/hooks', :controller => :hooks do
    post :newlead
  end
end

app/models/amo_account.rb
class AmoAccount < ApplicationRecord
  serialize :amo_data, JSON

  def amo_client
    Amorail::Client.new(usermail: usermail,
                        api_endpoint: api_endpoint,
                        api_key: api_key)
  end

  def amo_props
    props = nil
    Amorail.with_client(amo_client) do
      props = Amorail.properties
      # @leads = Amorail::Lead.find_by_query(responsible_user_id: "all")
      end
    props
  end

  def import_data_from_amo
    self.amo_data = amo_props.data
    # self.save
  end

  def amo_id
    self.amo_data["id"]
  end

  def amo_name
    self.amo_data["name"]
  end

  def amo_subdomain
    self.amo_data["subdomain"]
  end

  def amo_users_count
    self.amo_data['users'].count
  end

  def amo_users_limit
    self.amo_data['limits']['users_count']
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/amo_accounts_controller.rb
class AmoAccountsController < ApplicationController
  before_action :set_amo_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /amo_accounts
  # GET /amo_accounts.json
  def index
    @amo_accounts = AmoAccount.all
  end

  # GET /amo_accounts/1
  # GET /amo_accounts/1.json
  def show
  end

  # GET /amo_accounts/new
  def new
    @amo_account = AmoAccount.new
  end

  # GET /amo_accounts/1/edit
  def edit
  end

  # POST /amo_accounts
  # POST /amo_accounts.json
  def create
    @amo_account = AmoAccount.new(amo_account_params)
    @amo_account.import_data_from_amo
    respond_to do |format|
      if @amo_account.save
        format.html { redirect_to @amo_account, notice: 'Amo account was successfully created.' }
        format.json { render :show, status: :created, location: @amo_account }
      else
        format.html { render :new }
        format.json { render json: @amo_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amo_accounts/1
  # PATCH/PUT /amo_accounts/1.json
  def update
    @amo_account.import_data_from_amo
    respond_to do |format|
      if @amo_account.update(amo_account_params)
        format.html { redirect_to @amo_account, notice: 'Amo account was successfully updated.' }
        format.json { render :show, status: :ok, location: @amo_account }
      else
        format.html { render :edit }
        format.json { render json: @amo_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amo_accounts/1
  # DELETE /amo_accounts/1.json
  def destroy
    @amo_account.destroy
    respond_to do |format|
      format.html { redirect_to amo_accounts_url, notice: 'Amo account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amo_account
      @amo_account = AmoAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amo_account_params
      params.require(:amo_account).permit(:usermail, :api_endpoint, :api_key)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hooks_controller.rb
class HooksController

  def newlead
    if params[:account].present?
      # amo_account = AmoAccount.find
      # Survey.new(:name => params[:survey_name]
      # survey.url = params[:survey_url]
      # survey.creator_email = params[:survey_creator_email]
      # survey.save!
    end

    # The webhook doesn't require a response but let's make sure
    # we don't send anything
    render :nothing => true
  end

end

app/helpers/amo_accounts_helper.rb
module AmoAccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/amo_accounts/_form.html.haml
= form_for @amo_account do |f|
  - if @amo_account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@amo_account.errors.count, "error")} prohibited this amo_account from being saved:"
      %ul
        - @amo_account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :usermail
    = f.text_field :usermail
  .field
    = f.label :api_endpoint
    = f.text_field :api_endpoint
  .field
    = f.label :api_key
    = f.text_field :api_key
  .actions
    = f.submit 'Save'

app/views/amo_accounts/edit.html.haml
%h1 Editing amo_account

= render 'form'

= link_to 'Show', @amo_account
\|
= link_to 'Back', amo_accounts_path

app/views/amo_accounts/index.html.haml
.container
  .row
    .col-md-6
      .h1 Digecon amoCRM accounts

  .row
    .col-md-12
      %table.table.table-hover
        %thead
          %tr
            %th Usermail
            %th subdomain
            %th amo ID
            %th Name
            %th Users
            %th
            %th
            %th

        %tbody
          - @amo_accounts.each do |amo_account|
            %tr
              %td= amo_account.usermail
              %td= amo_account.amo_subdomain
              %td= amo_account.amo_id
              %td= amo_account.amo_name
              %td= "#{amo_account.amo_users_count} из #{amo_account.amo_users_limit}"
              %td= link_to 'Show', amo_account, class: "btn btn-xs btn-info"
              %td= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_amo_account_path(amo_account), class: "btn btn-xs btn-warning"
              %td= link_to  '<span class="glyphicon glyphicon-remove"></span>'.html_safe, amo_account, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-xs btn-danger"

  %br

  = link_to 'New Amo account', new_amo_account_path, class: "btn btn-primary"

app/views/amo_accounts/new.html.haml
%h1 New amo_account

= render 'form'

= link_to 'Back', amo_accounts_path

app/views/amo_accounts/show.html.haml
.container
  .row
    %p#notice= notice
    %p
      %b Usermail:
      = @amo_account.usermail
    %p
      %b Api endpoint:
      = @amo_account.api_endpoint

  .row
    .col-md-12
      %table.table.table-hover
        %thead
          %tr
            %th Аккаунт
            %th ID
            %th оплачен до
            %th Отделов
            %th Пользователей



        %tbody
          %tr
            %td= @amo_account.amo_data['name']
            %td= @amo_account.amo_data['id']
            %td= Time.at(@amo_account.amo_data['paid_till']) if @amo_account.amo_data['paid_till'] != nil
            %td= @amo_account.amo_data['groups'].count
            %td= "#{@amo_account.amo_data['users'].count} из #{@amo_account.amo_data['limits']['users_count']}"

.row
  .col-md-12
    %table.table.table-hover
      %thead
        %tr
          - @amo_account.amo_data['groups'].each do |group|
            %th= "#{group['name']}\n #{group['id']}"
      %tbody


    %b Amo Data
    = @amo_account.amo_data

  -# %p
  -#   %b custom fields
  -#   = raw JSON.pretty_generate(@props.data) #.gsub(" ","&nbsp;") #['custom_fields']['leads'].select {|field| field['name']=="Назначен менеджер"}


    = link_to 'Edit', edit_amo_account_path(@amo_account)
    \|
    = link_to 'Back', amo_accounts_path

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .table-responsive
      %table.table
        %tbody
          %tr
            %td
              .p.text-left
                = Time.now.year
                = icon('copyright')
                = link_to "DigEcon", root_path
            %td
              .p.text-center
                = icon('phone-square')
                8 (846) 215-01-04
            %td
              .p.text-right
                = icon('envelope')
                %a{:href => "mailto:#"} hello@digecon.ru

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      =current_user.email
      %span.caret
    %ul.dropdown-menu{:role => "menu"}
      -# - if current_user.try(:admin?)
      -#   %li= link_to t("users"), users_path
      %li= link_to current_user.email, edit_user_registration_path
      %li.divider
      %li
        = link_to t("devise.button.sign_out"), destroy_user_session_path, :method=>'delete'
- else
  %li= link_to t("devise.button.sign_in"), new_user_session_path
  %li= link_to t("devise.button.sign_up"), new_user_registration_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "DigEcon", root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/nav_links_for_auth'
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/_navigation_links.html.haml
-# <%# add navigation links to this file %>
-# %li= link_to t("about"), page_path('about')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DigEcon – Service App
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
      -# #modal-holder
    = render 'layouts/footer'